import { Roboto, Playwrite_HU } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";

const pwrite = Playwrite_HU({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={pwrite.className}
      >
        <Navbar/>
        <div className="min-h-screen">
        {children}
        </div>
      </body>
    </html>
  );
}
